# Opt-out flag for bundling Kotlin standard library -> https://jb.gg/intellij-platform-kotlin-stdlib
kotlin.stdlib.default.dependency = false
# Enable Gradle Configuration Cache -> https://docs.gradle.org/current/userguide/configuration_cache.html
org.gradle.configuration-cache = true
# Enable Gradle Build Cache -> https://docs.gradle.org/current/userguide/build_cache.html
org.gradle.caching = true

pluginRepositoryUrl = https://github.com/kizeevov/slint-idea-plugin

pluginGroup = dev.slint
pluginName = Slint
pluginVersion = 1.6.1
platformType = IU
platformVersion = 2024.2
pluginSinceBuild = 242
pluginUntilBuild = 262.*
platformPlugins =
pluginVerifierIdeVersions=2024.3,2025.1,2025.2,2025.3,2026.1,2026.2
jvmVersion = 21

slintLspVersion = 1.17.1
