[versions]
# libraries
annotations = "24.0.1"

# plugins
kotlin = "2.3.21"
changelog = "2.2.1"
intellij = "2.18.1"
grammarkit = "2023.3.0.3"
download = "5.7.0"

[libraries]
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
platform = { id = "org.jetbrains.intellij.platform", version.ref = "intellij" }
grammarkit = { id = "org.jetbrains.grammarkit", version.ref = "grammarkit" }
download = { id = "de.undercouch.download", version.ref = "download"}
