name: build plugin

on:
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v1

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
          distribution: corretto
          java-version: 17

    - name: Build rust plugin
      uses: gradle/gradle-build-action@v2
      with:
          arguments: ":plugin:buildPlugin"

    - name: Save artifacts
      uses: actions/upload-artifact@v3
      with:
          name: slint-idea-plugin
          path: plugin/build/distributions/*.zip
    
