name: build plugin

on:
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
          distribution: corretto
          java-version: 17

    - name: Build rust plugin
      uses: gradle/gradle-build-action@v2
      with:
          arguments: "buildPlugin"

    - name: Save artifacts
      uses: actions/upload-artifact@v3
      with:
          name: slint-idea-plugin
          path: /home/runner/work/slint-idea-plugin/slint-idea-plugin/build/distributions/*.zip
    
